set -gq @catppuccin_flavour                "dynamic"

set -g status-bg                          "#1e100d"
set -gq @thm_bar_bg                       "#1e100d"

set -gq @thm_bg                           "#1e100d"
set -gq @thm_fg                           "#f9dcd7"
set -gq @thm_primary                      "#ffb4a6"
set -gq @thm_inverse_primary              "#372623"
set -gq @thm_surface_low                  "#271815"
set -gq @thm_surface                      "#1e100d"
set -gq @thm_surface_variant              "#372623"
set -gq @thm_outline                      "#55423f"
set -gq @thm_text_variant                 "#dcc0bc"

set -g status-style                       "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g window-active-style                "bg=#{@thm_bg},fg=#{@thm_fg}"
