set -gq @catppuccin_flavour                "dynamic"

set -g status-bg                          "#1c1014"
set -gq @thm_bar_bg                       "#1c1014"

set -gq @thm_bg                           "#1c1014"
set -gq @thm_fg                           "#f5dce2"
set -gq @thm_primary                      "#ffb0c9"
set -gq @thm_inverse_primary              "#35262a"
set -gq @thm_surface_low                  "#25181c"
set -gq @thm_surface                      "#1c1014"
set -gq @thm_surface_variant              "#35262a"
set -gq @thm_outline                      "#534247"
set -gq @thm_text_variant                 "#d8c1c6"

set -g status-style                       "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g window-active-style                "bg=#{@thm_bg},fg=#{@thm_fg}"
